Repository treehouses/cli, pull requests merged in 2018-06, with the labels that each got.

#108 Improve npmjs tags (fixes #107)
  package.json
Labels: in progress

#102 add new line to expanded help
  cli.sh
  package.json
Labels: in progress

#93 treehouses help vnc
  cli.sh
Labels: done

#92 treehouses help ssh
  cli.sh
Labels: done

#91 treehouses help locale
  cli.sh
Labels: done

#78 treehouses help expandfs
  cli.sh
Labels: done

#87 treehouses help container
  cli.sh
Labels: done

#90 treehouses help timezone
  cli.sh
Labels: done

#86 treehouses help bridge
  cli.sh
Labels: done, in progress

#112 Create LICENSE
  LICENSE
Labels: in progress

#115 Create .gitignore
  .gitignore
Labels: in progress

#116 version 0.3.0
  package.json
Labels: in progress
