Repository treehouses/cli, pull requests merged in 2018-07, with the labels that each got.

#120 Add version validation and -force upgrade (fixes #119)
  cli.sh
  package.json
Labels: in progress

#125 treehouses sshtunnel (Fixes #122)
  cli.sh
  package.json
  templates/rc.local/bridge
  templates/rc.local/default
  templates/rc.local/hotspot
Labels: in progress

#127 update package.json
  package.json
Labels: in progress

#130 fixes & version 0.3.4 (fixes #129)
  cli.sh
  package.json
Labels: in progress

#132 Add image version to CLI (fixes #105)
  cli.sh
Labels: in progress, ready to merge

#134 fixes in SSHtunnel expanded help
  cli.sh
Labels: ready to merge

#135 add missing commands to readme (fixes #133)
  README.md
Labels: in progress

#126 treehouses wificountry (fixes #97)
  cli.sh
Labels: in progress, ready to merge

#136 treehouses led
  cli.sh
Labels: ready to merge
