Repository treehouses/cli, pull requests merged in 2020-06, with the labels that each got.

#1385 `treehouses camera on` & `off` refactor (fixes #1300)
  modules/camera.sh
  package.json
Labels: high priority, please test & review

#1369 `treehouses camera detect` v2 (fixes #1368)
  modules/camera.sh
  package.json
Labels: high priority, please test & review

#1313 `treehouses camera record` (fixes #1225)
  README.md
  modules/camera.sh
  modules/help.sh
  package.json
Labels: high priority, please test & review

#1386 improve `checkwrpi` function (fixes #1379)
  modules/globals.sh
  package.json
Labels: high priority, please test & review

#1406 `treehouses help magazine`
  modules/magazine.sh
  package.json
Labels: please test & review

#1327 `treehouses resolution` (fixes #1227)
  README.md
  _treehouses
  modules/help.sh
  modules/resolution.sh
  package.json
Labels: high priority, please test & review

#1419 `treehouses sshkey add` check (fixes #1281)
  modules/sshkey.sh
  package.json
Labels: high priority, please test & review

#1432 `treehouses upgrade cli` sudo (fixes #1378) (fixes #1417)
  modules/upgrade.sh
  package.json
Labels: high priority, please test & review

#1424 `treehouses magazine` moved checkinternet (fixes #1414)
  modules/magazine.sh
  package.json
Labels: high priority, please test & review

#1425 `treehouses magazine helloworld` (fixes #1381)
  README.md
  _treehouses
  modules/help.sh
  modules/magazine.sh
  package.json
  tests/magazine.bats
Labels: enhancement, high priority, please test & review

#1405 `treehouse services bookstack` (fixes #1340)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-bookstack.sh
  tests/services/bookstack.bats
Labels: high priority, please test & review

#1438 `treehouses services transmission` (fixes #1422)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-transmission.sh
  tests/services/transmission.bats
Labels: high priority, please test & review

#1290 `treehouses wifi` & `wifihidden` enterprise (fixes #431)
  README.md
  modules/help.sh
  modules/wifi.sh
  modules/wifihidden.sh
  package.json
Labels: enhancement, high priority, please test & review

#1450 `treehouses wifi` enterprise addition (fixes #1452)
  modules/wifi.sh
  package.json
Labels: high priority, please test & review

#1444 `treehouses services cloud9` (fixes #1420)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-cloud9.sh
  tests/services/cloud9.bats
Labels: high priority, please test & review

#1439 `treehouses services dokuwiki` (fixes #1423)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-dokuwiki.sh
  tests/services/dokuwiki.bats
Labels: high priority, please test & review

#1437 `treehouses services mongodb` init (fixes #1436)
  package.json
  services/install-mongodb.sh
Labels: high priority, please test & review

#1370 `treehouses camera detect` coral (fixes #1364)
  modules/camera.sh
  package.json
Labels: high priority, please test & review

#1411 `treehouses inspire fact` (fixes #1410)
  README.md
  _treehouses
  modules/help.sh
  modules/inspire.sh
  package.json
Labels: enhancement, high priority, please test & review

#1454 `treehouses magazine` tests (fixes #1453)
  package.json
  tests/magazine.bats
  tests/magazine/hackspace.bats
  tests/magazine/helloworld.bats
  tests/magazine/magpi.bats
  tests/magazine/wireframe.bats
  tests/test.sh
Labels: major, please test & review

#1312 `treehouses sshtunnel` refactor (fixes #1198)
  README.md
  _treehouses
  modules/default.sh
  modules/help.sh
  modules/sshtunnel.sh
  package.json
Labels: in progress

#1472 `treehouses sshtunnel remove port` external (fixes #1471)
  modules/sshtunnel.sh
  package.json
Labels: high priority, please test & review

#1433 `treehouses services` for multi-arch (fixes #1416)
  README.md
  _treehouses
  modules/detect.sh
  modules/help.sh
  modules/services.sh
  package.json
  services/README.md
  services/install-bookstack.sh
  services/install-cloud9.sh
  services/install-couchdb.sh
  services/install-dokuwiki.sh
  services/install-grocy.sh
  services/install-invoiceninja.sh
  services/install-kolibri.sh
  services/install-librespeed.sh
  services/install-mariadb.sh
  services/install-mastodon.sh
  services/install-minetest.sh
  services/install-mongodb.sh
  services/install-moodle.sh
  services/install-musicblocks.sh
  services/install-netdata.sh
  services/install-nextcloud.sh
  services/install-ntopng.sh
  services/install-pihole.sh
  services/install-planet.sh
  services/install-portainer.sh
  services/install-privatebin.sh
  services/install-seafile.sh
  services/install-transmission.sh
  services/install-turtleblocksjs.sh
Labels: high priority, in progress, major

#1474 `treehouses help sshtunnel` improve (fixes #1473)
  modules/sshtunnel.sh
  package.json
Labels: please test & review

#1457 `treehouses magazine` refactor (fixes #1456)
  _treehouses
  cli.sh
  magazine/download-hackspace.sh
  magazine/download-helloworld.sh
  magazine/download-magpi.sh
  magazine/download-wireframe.sh
  modules/magazine.sh
  package.json
Labels: high priority, major, please test & review

#1485 `treehouses sshtunnel active` (fixes #1478)
  README.md
  _treehouses
  modules/help.sh
  modules/sshtunnel.sh
  package.json
Labels: high priority, please test & review

#1501 `treehouses magazine` completion (fixes #1500)
  _treehouses
  package.json
Labels: high priority, please test & review

#1502 `treehouses remote commands [json]` (fixes #1499)
  _treehouses
  package.json
Labels: please test & review

#1510 `treehouses magazine` un-`set -e` (fixes #1503) (fixes #1509)
  magazine/download-hackspace.sh
  magazine/download-helloworld.sh
  magazine/download-magpi.sh
  magazine/download-wireframe.sh
  modules/magazine.sh
  package.json
Labels: please test & review

#1484 `treehouses sshtunnel` incrementing monitor port (fixes #1482)
  modules/sshtunnel.sh
  package.json
Labels: high priority, please test & review

#1497 `treehouses sshtunnel key verify` (fixes #1490)
  _treehouses
  modules/sshtunnel.sh
  package.json
Labels: please test & review

#1542 `treehouses led` tests (fixes #1524)
  tests/led.bats
  tests/led/carnival.bats
  tests/led/christmas.bats
  tests/led/dance.bats
  tests/led/diwali.bats
  tests/led/easter.bats
  tests/led/eid.bats
  tests/led/green.bats
  tests/led/heavymetal.bats
  tests/led/kecak.bats
  tests/led/lantern.bats
  tests/led/led-green.bats
  tests/led/lunarnewyear.bats
  tests/led/newyear.bats
  tests/led/onam.bats
  tests/led/random.bats
  tests/led/red-default-on.bats
  tests/led/red.bats
  tests/led/stpatricks.bats
  tests/led/thanksgiving.bats
  tests/led/valentine.bats
Labels: in progress

#1549 `treehouses sshtunnel ports` (fixes #1547)
  README.md
  _treehouses
  modules/help.sh
  modules/sshtunnel.sh
  package.json
Labels: please test & review

#1550 `treehouses sshtunnel` send notice on ports change (fixes #1545)
  modules/sshtunnel.sh
Labels: please test & review

#1489 `treehouses sshtunnel refresh` (fixes #1488)
  README.md
  _treehouses
  modules/help.sh
  modules/sshtunnel.sh
  package.json
Labels: please test & review
