Repository treehouses/cli, pull requests merged in 2020-07, with the labels that each got.

#1458 `treehouses services piwigo` (fixes #1421)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-piwigo.sh
  tests/services/piwigo.bats
Labels: high priority, please test & review

#1546 `treehouses magazine` refactor (fixes #1496)
  _treehouses
  magazine/download-hackspace.sh
  magazine/download-helloworld.sh
  magazine/download-magpi.sh
  magazine/download-wireframe.sh
  modules/magazine.sh
  package.json
Labels: high priority, major, please test & review

#1579 `treehouses ssh` refactor (fixes #1578)
  modules/ssh.sh
  package.json
Labels: please test & review

#1581 `treehouses usb` refactor (fixes #1580)
  modules/usb.sh
  package.json
Labels: please test & review

#1583 `treehouses bluetooth` refactor (fixes #1582)
  modules/bluetooth.sh
  package.json
Labels: please test & review

#1605 `treehouses magazines` (fixes #1589)
  README.md
  _treehouses
  cli.sh
  magazines/download-hackspace.sh
  magazines/download-helloworld.sh
  magazines/download-magpi.sh
  magazines/download-wireframe.sh
  modules/help.sh
  modules/magazine.sh
  modules/magazines.sh
  package.json
  tests/magazine/helloworld.bats
  tests/magazines/hackspace.bats
  tests/magazines/helloworld.bats
  tests/magazines/magpi.bats
  tests/magazines/wireframe.bats
  tests/test.sh
Labels: high priority, major, please test & review

#1611 `treehouses magazines` code climate (fixes #1606)
  magazines/download-hackspace.sh
  magazines/download-helloworld.sh
  magazines/download-wireframe.sh
  package.json
Labels: high priority, please test & review

#1622 `treehouses led` refactor tests (fixes #1524)
  package.json
  tests/led.bats
  tests/led/carnival.bats
  tests/led/christmas.bats
  tests/led/dance.bats
  tests/led/defaultled.bats
  tests/led/defaultred.bats
  tests/led/diwali.bats
  tests/led/dragonboat.bats
  tests/led/easter.bats
  tests/led/eid.bats
  tests/led/green.bats
  tests/led/heavymetal.bats
  tests/led/independenceday.bats
  tests/led/kecak.bats
  tests/led/lantern.bats
  tests/led/lunarnewyear.bats
  tests/led/newyear.bats
  tests/led/onam.bats
  tests/led/random.bats
  tests/led/red.bats
  tests/led/stpatricks.bats
  tests/led/thanksgiving.bats
  tests/led/valentine.bats
  tests/test.sh
Labels: please test & review

#1627 `treehouses help power` (fixes #1599)
  modules/power.sh
  package.json
Labels: please test & review

#1552 `treehouses picture` (fixes #1491)
  README.md
  _treehouses
  modules/help.sh
  modules/picture.sh
  package.json
  tests/picture.bats
Labels: high priority, please test & review

#1619 `treehouses magazines` refactor (fixes #1618)
  magazines/download-hackspace.sh
  magazines/download-helloworld.sh
  magazines/download-magpi.sh
  magazines/download-wireframe.sh
  modules/magazines.sh
  package.json
Labels: high priority, please test & review

#1608 `treehouses magazines available` (fixes #1594)
  README.md
  _treehouses
  modules/help.sh
  modules/magazines.sh
  package.json
Labels: high priority, please test & review

#1565 `treehouses bluetooth status` (fixes #1555)
  modules/bluetooth.sh
  package.json
Labels: high priority, please test & review

#1621 `treehouses shadowsocks` (fixes #1596)
  README.md
  _treehouses
  modules/default.sh
  modules/help.sh
  modules/shadowsocks.sh
  package.json
  templates/network/proxychains4.conf
  templates/network/shadowsocks.json
  tests/shadowsocks.bats
Labels: high priority, please test & review

#1629 `treehouses discover gateway` (fixes #510)
  README.md
  _treehouses
  modules/discover.sh
  modules/help.sh
  package.json
  tests/discover.bats
Labels: high priority, please test & review

#1492 `treehouses system`
  README.md
  _treehouses
  modules/help.sh
  modules/system.sh
  package.json
  tests/system.bats
Labels: high priority, please test & review

#1624 `treehouses memory` no slash commands (fixes #1557)
  README.md
  modules/help.sh
  modules/memory.sh
  package.json
Labels: please test & review

#1576 `treehouses services pylon` (fixes #1556)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-pylon.sh
  tests/services/pylon.bats
Labels: high priority, please test & review

#1620 `treehouses tor ports` no ports
  modules/tor.sh
  package.json
Labels: please test & review

#1632 `treehouses magazines downloaded` (fixes #1595)
  README.md
  _treehouses
  magazines/download-hackspace.sh
  magazines/download-helloworld.sh
  magazines/download-magpi.sh
  magazines/download-wireframe.sh
  modules/help.sh
  modules/magazines.sh
  package.json
Labels: enhancement, high priority, please test & review

#1635 `treehouses magazines <magtype> list` (fixes #1631)
  README.md
  _treehouses
  modules/help.sh
  modules/magazines.sh
  package.json
  tests/magazines/hackspace.bats
  tests/magazines/helloworld.bats
  tests/magazines/magpi.bats
  tests/magazines/wireframe.bats
Labels: enhancement, high priority, please test & review

#1636 `treehouses magazines <magtype>` links (fixes #1634)
  magazines/download-hackspace.sh
  magazines/download-helloworld.sh
  magazines/download-magpi.sh
  magazines/download-wireframe.sh
  package.json
Labels: high priority, please test & review

#1638 `treehouses help discover` refactor (fixes #1630)
  modules/discover.sh
  package.json
Labels: high priority, please test & review

#1633 `treehouses picture` check (fixes #1628)
  modules/picture.sh
  package.json
Labels: please test & review

#1251 `treehouses uptime` (fixes #1250)
  README.md
  _treehouses
  modules/help.sh
  modules/uptime.sh
  package.json
  tests/uptime.bats
Labels: high priority, please test & review

#1587 `treehouses tor` refactor (fixes #1574)
  README.md
  _treehouses
  modules/help.sh
  modules/tor.sh
  package.json
Labels: high priority, please test & review

#1332 `treehouses tether` (fixes #1316)
  README.md
  _treehouses
  modules/default.sh
  modules/help.sh
  modules/networkmode.sh
  modules/tether.sh
  package.json
  tests/tether.bats
Labels: high priority, please test & review

#1651 `treehouses services librespeed` less env (fixes #1649)
  package.json
  services/install-librespeed.sh
Labels: please test & review

#1650 `treehouses services grocy` less env (fixes #1648)
  package.json
  services/install-grocy.sh
Labels: please test & review

#1625 `treehouses services jellyfin` (fixes #1613)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-jellyfin.sh
  tests/services/jellyfin.bats
Labels: please test & review

#1670 `treehouses memory` completion (fixes #1669)
  _treehouses
  package.json
Labels: high priority, please test & review

#1644 `treehouses internet` refactor
  modules/internet.sh
  package.json
Labels: please test & review

#1659 `treehouses uptime log` (fixes #1645)
  README.md
  _treehouses
  modules/help.sh
  modules/uptime.sh
  package.json
Labels: please test & review

#1617 `treehouses services` refactor (fixes #1616)
  modules/services.sh
  package.json
Labels: please test & review

#1676 `treehouses memory` no dash outputs (fixes #1671)
  modules/memory.sh
  package.json
Labels: high priority, please test & review

#1675 `treehouses magazines` `README.md` added (fixes #1642)
  magazines/README.md
  modules/magazines.sh
  package.json
Labels: high priority, please test & review

#1683 `treehouses discover self` (fixes #1652)
  README.md
  _treehouses
  modules/discover.sh
  modules/help.sh
  package.json
  tests/discover.bats
Labels: please test & review

#1678 `treehouses magazines <magtype> url` (fixes #1641)
  README.md
  _treehouses
  magazines/download-hackspace.sh
  magazines/download-helloworld.sh
  magazines/download-magpi.sh
  magazines/download-wireframe.sh
  modules/help.sh
  modules/magazines.sh
  package.json
  tests/magazines/hackspace.bats
  tests/magazines/helloworld.bats
  tests/magazines/magpi.bats
  tests/magazines/wireframe.bats
Labels: enhancement, high priority, major, please test & review

#1663 `treehouses message gitter apikey` (fixes #1694)
  modules/message.sh
  package.json
Labels: please test & review

#1685 `treehouses services pylon` with env (fixes #1682)
  package.json
  services/install-pylon.sh
Labels: please test & review

#1665 `treehouses upgrade bluetooth` targeted kill (fixes #1607)
  modules/upgrade.sh
  package.json
Labels: please test & review

#1526 `treehouses sshtunnel`/`remote` send/receive keys (fixes #1512)
  README.md
  _treehouses
  modules/help.sh
  modules/remote.sh
  modules/sshtunnel.sh
  package.json
Labels: please test & review

#1677 `treehouses services webssh` (fixes #1661)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-webssh.sh
  tests/services/webssh.bats
Labels: please test & review

#1696 `treehouses message gitter receivefrom` (fixes #1686)
  README.md
  _treehouses
  modules/help.sh
  modules/message.sh
  package.json
Labels: please test & review

#1597 `treehouses services rutorrent` (fixes #1527)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-rutorrent.sh
  tests/services/rutorrent.bats
Labels: in progress

#1553 `treehouses redirect` (fixes #1493)
  README.md
  _treehouses
  modules/default.sh
  modules/help.sh
  modules/redirect.sh
  package.json
Labels: high priority, please test & review

#1667 global: `check_missing_binary` added (fixes #1657)
  modules/globals.sh
  modules/picture.sh
  modules/usb.sh
  package.json
Labels: please test & review

#1718 `treehouses sshtunnel` no output if notice enabled (fixes #1717)
  modules/sshtunnel.sh
  package.json
Labels: high priority, please test & review

#1729 `treehouses sshkey delete` refactor (fixes #1712)
  modules/sshkey.sh
  package.json
Labels: please test & review

#1713 `treehouses magazines` refactor (fixes #1637)
  modules/magazines.sh
  package.json
Labels: high priority, please test & review
