Repository treehouses/cli, pull requests merged in 2020-02, with the labels that each got.

#645 treehouses tor refresh (fixes #622)
  README.md
  _treehouses
  modules/help.sh
  modules/tor.sh
  package.json
Labels: please review

#641 update README.md (fixes #640)
  README.md
  package.json
Labels: done, enhancement, ready to merge

#646 compose-ify the services portainer and nextcloud (fixes #614)(fixes #615)
  modules/services.sh
  package.json
  templates/services/nextcloud/nextcloud_autorun
  templates/services/nextcloud/nextcloud_yml.sh
  templates/services/portainer/portainer_autorun
  templates/services/portainer/portainer_yml.sh
Labels: high priority, please review

#608 treehouses wifi and wifihidden with checkwifi (fixes #575)
  modules/globals.sh
  modules/wifi.sh
  modules/wifihidden.sh
  package.json
Labels: high priority, please review

#660 treehouses services url with networkmode info (fixes #649)
  modules/services.sh
  package.json
Labels: please review

#644 treehouses services with check_space (fixes #621)
  modules/services.sh
  package.json
Labels: high priority, please review

#656 treehouses services ntopng added (fixes #618)
  modules/services.sh
  package.json
  templates/services/ntopng/ntopng_autorun
Labels: done, high priority, please review

#667 remove shebang from sources (fixes #666)
  .codeclimate.yml
  modules/ap.sh
  modules/apchannel.sh
  modules/aphidden.sh
  modules/bluetooth.sh
  modules/bluetoothid.sh
  modules/bootoption.sh
  modules/bridge.sh
  modules/burn.sh
  modules/button.sh
  modules/camera.sh
  modules/clone.sh
  modules/config.sh
  modules/container.sh
  modules/coralenv.sh
  modules/cron.sh
  modules/default.sh
  modules/detect.sh
  modules/detectrpi.sh
  modules/discover.sh
  modules/ethernet.sh
  modules/expandfs.sh
  modules/feedback.sh
  modules/globals.sh
  modules/help.sh
  modules/image.sh
  modules/internet.sh
  modules/led.sh
  modules/locale.sh
  modules/log.sh
  modules/memory.sh
  modules/networkmode.sh
  modules/ntp.sh
  modules/openvpn.sh
  modules/password.sh
  modules/rebootneeded.sh
  modules/reboots.sh
  modules/remote.sh
  modules/rename.sh
  modules/restore.sh
  modules/rtc.sh
  modules/services.sh
  modules/speedtest.sh
  modules/ssh.sh
  modules/sshkey.sh
  modules/sshtunnel.sh
  modules/staticwifi.sh
  modules/temperature.sh
  modules/timezone.sh
  modules/tor.sh
  modules/upgrade.sh
  modules/usb.sh
  modules/verbose.sh
  modules/version.sh
  modules/vnc.sh
  modules/wifi.sh
  modules/wificountry.sh
  modules/wifihidden.sh
  modules/wifistatus.sh
Labels: done, enhancement

#662 treehouses services error handling
  modules/services.sh
  package.json
Labels: high priority, please review

#665 localize function variables (fixes #664)
  modules/ap.sh
  modules/apchannel.sh
  modules/aphidden.sh
  modules/bluetooth.sh
  modules/bluetoothid.sh
  modules/bootoption.sh
  modules/bridge.sh
  modules/burn.sh
  modules/button.sh
  modules/camera.sh
  modules/clone.sh
  modules/config.sh
  modules/coralenv.sh
  modules/cron.sh
  modules/detectrpi.sh
  modules/discover.sh
  modules/feedback.sh
  modules/globals.sh
  modules/led.sh
  modules/locale.sh
  modules/log.sh
  modules/memory.sh
  modules/networkmode.sh
  modules/ntp.sh
  modules/openvpn.sh
  modules/remote.sh
  modules/rename.sh
  modules/restore.sh
  modules/rtc.sh
  modules/services.sh
  modules/ssh.sh
  modules/sshkey.sh
  modules/sshtunnel.sh
  modules/staticwifi.sh
  modules/temperature.sh
  modules/timezone.sh
  modules/tor.sh
  modules/upgrade.sh
  modules/usb.sh
  modules/vnc.sh
  modules/wifi.sh
  modules/wificountry.sh
  modules/wifihidden.sh
  modules/wifistatus.sh
  package.json
Labels: done, enhancement, high priority

#677 treehouses wificountry (fixes #676)
  modules/wificountry.sh
  package.json
Labels: enhancement, please review

#658 treehouses blocker (fixes #657) (fixes #157)
  .codeclimate.yml
  .travis.yml
  README.md
  _treehouses
  cli.sh
  modules/blocker.sh
  modules/config.sh
  modules/help.sh
  package.json
  templates/blocker/blocker.sh
Labels: done, enhancement, please review

#695 treehouses detectrpi model (fixes #643)
  README.md
  _treehouses
  cli.sh
  modules/detectrpi.sh
  modules/help.sh
  package.json
Labels: enhancement, please review

#703 check for bc pkg in temperature & memory (fixes #554)
  modules/memory.sh
  modules/temperature.sh
  package.json
Labels: high priority, please review

#707 treehouses led no locals (fixes #706)
  modules/led.sh
  package.json
Labels: bug, high priority

#702 treehouses service mastodon (fixes #672)
  modules/services.sh
  package.json
  templates/services/mastodon/mastodon_autorun
  templates/services/mastodon/mastodon_yml.sh
Labels: high priority, please review

#723 treehouses led carnival spelling (fixes #717)
  modules/led.sh
  package.json
Labels: ready to merge

#674 treehouses services ntopng with compose (fixes #669)
  modules/services.sh
  package.json
  templates/services/ntopng/ntopng_yml.sh
Labels: done, high priority, please review

#729 treehouses services add tor port using screen (fixes #698)
  modules/services.sh
  package.json
Labels: please review

#732 treehouses remote minimum version check (fixes #728)
  _treehouses
  modules/help.sh
  modules/remote.sh
  package.json
Labels: high priority, please review

#740 treehouses help & help services servicenames (fixes #711)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
Labels: enhancement, please review
