Repository treehouses/cli, pull requests merged in 2020-01, with the labels that each got.

#562 update detectrpi.sh (fixes #565)
  modules/detectrpi.sh
  package.json
Labels: done

#563 treehouses bridge less dnsmasq comments
  templates/network/dnsmasq/default
Labels: done

#552 update globals.sh with checkwrpi (fixes #550)
  cli.sh
  modules/globals.sh
  package.json
Labels: high priority

#532 treehouses ap/bridge hotspotname rfc check (fixes #528)
  modules/ap.sh
  modules/bridge.sh
  modules/password.sh
  modules/wifi.sh
  package.json
Labels: done, high priority, please review

#577 globals: new check missing packages (fixes #576)
  modules/globals.sh
  package.json
Labels: please review

#571 treehouses wifihidden (fixes #570)
  README.md
  _treehouses
  cli.sh
  modules/help.sh
  modules/wifihidden.sh
  package.json
Labels: please review

#572 update package.json (fixes #573)
  package.json
Labels: please review

#578 treehouses services privatebin added
  modules/services.sh
  package.json
  templates/services/privatebin/privatebin_autorun
  templates/services/privatebin/privatebin_yml.sh
Labels: please review

#543 treehouses usb [on|off] added (fixes #538)
  README.md
  _treehouses
  cli.sh
  modules/help.sh
  modules/usb.sh
  package.json
Labels: needs more work

#586 treehouses led carneval (fixes #593)
  _treehouses
  modules/led.sh
  package.json
Labels: done

#587 treehouses services additions (fixes #569)
  _treehouses
  modules/services.sh
  package.json
Labels: please review

#588 treehouses help unify (fixes #589)
  modules/ap.sh
  modules/apchannel.sh
  modules/bluetooth.sh
  modules/bluetoothid.sh
  modules/bootoption.sh
  modules/bridge.sh
  modules/burn.sh
  modules/button.sh
  modules/camera.sh
  modules/clone.sh
  modules/container.sh
  modules/coralenv.sh
  modules/default.sh
  modules/detect.sh
  modules/detectrpi.sh
  modules/discover.sh
  modules/ethernet.sh
  modules/expandfs.sh
  modules/feedback.sh
  modules/globals.sh
  modules/image.sh
  modules/internet.sh
  modules/locale.sh
  modules/memory.sh
  modules/networkmode.sh
  modules/ntp.sh
  modules/openvpn.sh
  modules/password.sh
  modules/rebootneeded.sh
  modules/reboots.sh
  modules/rename.sh
  modules/restore.sh
  modules/rtc.sh
  modules/services.sh
  modules/speedtest.sh
  modules/ssh.sh
  modules/sshkey.sh
  modules/sshtunnel.sh
  modules/staticwifi.sh
  modules/temperature.sh
  modules/timezone.sh
  modules/tor.sh
  modules/upgrade.sh
  modules/usb.sh
  modules/version.sh
  modules/vnc.sh
  modules/wifi.sh
  modules/wificountry.sh
  modules/wifihidden.sh
  modules/wifistatus.sh
  package.json
Labels: high priority, please review

#580 treehouses verbose added (fixes #169)
  README.md
  _treehouses
  cli.sh
  modules/ap.sh
  modules/bootoption.sh
  modules/coralenv.sh
  modules/default.sh
  modules/ethernet.sh
  modules/expandfs.sh
  modules/feedback.sh
  modules/globals.sh
  modules/help.sh
  modules/led.sh
  modules/locale.sh
  modules/ntp.sh
  modules/openvpn.sh
  modules/rtc.sh
  modules/sshtunnel.sh
  modules/staticwifi.sh
  modules/timezone.sh
  modules/verbose.sh
  modules/wifi.sh
  modules/wificountry.sh
  modules/wifihidden.sh
  package.json
Labels: please review

#602 treehouses verbose 3rd (fixes #600)
  cli.sh
  package.json
Labels: high priority

#603 treehouses services portainer
  modules/services.sh
  package.json
  templates/services/portainer/portainer_autorun
Labels: needs more work

#597 treehouses aphidden (fixes #581)
  README.md
  _treehouses
  cli.sh
  modules/aphidden.sh
  modules/help.sh
  package.json
  templates/network/hostapd/no_password_hidden
  templates/network/hostapd/password_hidden
Labels: please review

#617 treehouses led valentine (fixes #591)
  _treehouses
  modules/led.sh
  package.json
Labels: high priority, please review

#619 treehouses tor start port check (fixes #612)
  modules/tor.sh
  package.json
Labels: please review

#613 treehouses services ports & urls (fixes #605) (fixes #606)
  modules/services.sh
  package.json
Labels: please review

#611 treehouses log (fixes #599)
  README.md
  _treehouses
  cli.sh
  modules/apchannel.sh
  modules/bluetooth.sh
  modules/bluetoothid.sh
  modules/bootoption.sh
  modules/bridge.sh
  modules/burn.sh
  modules/camera.sh
  modules/clone.sh
  modules/config.sh
  modules/container.sh
  modules/coralenv.sh
  modules/cron.sh
  modules/default.sh
  modules/detect.sh
  modules/detectrpi.sh
  modules/discover.sh
  modules/ethernet.sh
  modules/expandfs.sh
  modules/feedback.sh
  modules/globals.sh
  modules/help.sh
  modules/image.sh
  modules/internet.sh
  modules/led.sh
  modules/locale.sh
  modules/log.sh
  modules/memory.sh
  modules/networkmode.sh
  modules/ntp.sh
  modules/openvpn.sh
  modules/password.sh
  modules/rebootneeded.sh
  modules/reboots.sh
  modules/remote.sh
  modules/rename.sh
  modules/restore.sh
  modules/rtc.sh
  modules/speedtest.sh
  modules/ssh.sh
  modules/sshkey.sh
  modules/sshtunnel.sh
  modules/staticwifi.sh
  modules/temperature.sh
  modules/timezone.sh
  modules/tor.sh
  modules/upgrade.sh
  modules/usb.sh
  modules/verbose.sh
  modules/version.sh
  modules/vnc.sh
  modules/wifi.sh
  modules/wificountry.sh
  modules/wifihidden.sh
  modules/wifistatus.sh
  package.json
Labels: done, high priority, please review
