Repository treehouses/cli, pull requests merged in 2020-05, with the labels that each got.

#1163 `treehouses help` add led festivities (fixes #849)
  README.md
  modules/help.sh
  package.json
Labels: please test & review

#1166 update README.md in services (fixes #1159)
  package.json
  services/README.md
Labels: please test & review

#1147 `treehouses power` (fixes #1052)
  README.md
  _treehouses
  modules/help.sh
  modules/led.sh
  modules/power.sh
  package.json
Labels: high priority, please test & review

#1189 `treehouses tor notice now` refactor (fixes #1186)
  modules/tor.sh
  package.json
Labels: high priority, ready to merge

#1155 `treehouses discover wifi` (fixes #996)
  README.md
  _treehouses
  modules/discover.sh
  modules/help.sh
  package.json
  tests/discover.bats
Labels: high priority, please test & review

#1167 `treehouses discover` refactor (fixes #1161)
  modules/discover.sh
  package.json
Labels: high priority, please test & review

#1144 `treehouses services <service> install` sleepy try (fixes #946)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#1139 `treehouses detect` combinator (fixes #955)
  README.md
  _treehouses
  modules/detect.sh
  modules/detectarm.sh
  modules/detectbluetooth.sh
  modules/detectrpi.sh
  modules/detectwifi.sh
  modules/help.sh
  tests/detect.bats
  tests/detectarm.bats
  tests/detectbluetooth.bats
  tests/detectrpi.bats
  tests/detectwifi.bats
  tests/test.sh
Labels: enhancement, major, please test & review

#1201 treehouses services environment edit "non-interactive" (fixes #1165)
  _treehouses
  modules/services.sh
  package.json
Labels: please test & review

#1158 `treehouses upgrade cli <branch>` (fixes #1153)
  README.md
  _treehouses
  modules/help.sh
  modules/upgrade.sh
  package.json
  tests/upgrade.bats
Labels: please test & review

#1187 `treehouses services musicblocks`
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-musicblocks.sh
Labels: high priority, please test & review

#1162 `treehouses bootoption params` & `modules` (fixes #1000)
  README.md
  _treehouses
  modules/bootoption.sh
  modules/help.sh
  package.json
Labels: please test & review

#1150 `treehouses services minetest` (fixes #991)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-minetest.sh
Labels: please test & review

#1145 update Vagrantfile (fixes #1146)
  Vagrantfile
  package.json
Labels: please test & review

#1240 `treehouses services <service> start` (fixes #1224)
  modules/services.sh
  package.json
Labels: please test & review

#1247 update Vagrantfile (fixes #1246)
  Vagrantfile
  package.json
Labels: high priority, please test & review

#1188 `treehouses services <service>` (fixes #965)
  _treehouses
  modules/services.sh
Labels: high priority, please test & review

#1148 treehouses services multiple env (fixes #1112)
  README.md
  _treehouses
  modules/help.sh
  modules/services.sh
  package.json
Labels: high priority, please test & review

#1239 treehouses services env check (fixes #1237)
  modules/services.sh
  package.json
Labels: please test & review

#1160 `treehouses gpio` (fixes #1154)
  README.md
  _treehouses
  modules/gpio.sh
  modules/help.sh
  package.json
  tests/gpio.bats
Labels: please test & review

#1249 treehouses remote help json (fixes #1241)
  modules/remote.sh
  package.json
Labels: high priority, please test & review

#1257 whitespaces (fixes #1256)
  modules/expandfs.sh
  modules/image.sh
  modules/ssh.sh
  modules/staticwifi.sh
  modules/timezone.sh
Labels: high priority, please test & review

#1263 tests: `treehouses services <service> start` (fixes #1243)
  package.json
  tests/services.bats
  tests/services/couchdb.bats
  tests/services/kolibri.bats
  tests/services/mariadb.bats
  tests/services/mastodon.bats
  tests/services/mongodb.bats
  tests/services/moodle.bats
  tests/services/netdata.bats
  tests/services/nextcloud.bats
  tests/services/ntopng.bats
  tests/services/pihole.bats
  tests/services/portainer.bats
  tests/services/privatebin.bats
  tests/services/seafile.bats
Labels: please test & review

#1265 tests: more services (fixes #1262)
  package.json
  tests/services/minetest.bats
  tests/services/musicblocks.bats
  tests/services/turtleblocksjs.bats
Labels: please test & review

#1255 `treehouses services mariadb icon` refactor
  package.json
  services/install-mariadb.sh
Labels: high priority, please test & review

#1254 `treehouses services privatebin icon` refactor
  package.json
  services/install-privatebin.sh
Labels: high priority, please test & review

#1259 update `Vagrantfile` to treehouses/buster 0.13.3 (fixes #1258)
  Vagrantfile
  package.json
Labels: high priority, please test & review

#1261 `treehouses services <service> config` (fixes #1114)
  README.md
  _treehouses
  modules/help.sh
  modules/services.sh
  package.json
Labels: high priority, please test & review

#1267 `checkwrpi` detect bluetooth (fixes #1266)
  modules/globals.sh
  package.json
Labels: high priority, please test & review

#1108 `treehouses wifi` print ip address (fixes #1073)
  modules/wifi.sh
  package.json
Labels: enhancement, high priority, please test & review

#1178 `treehouses ssh` (fixes #995)
  README.md
  modules/help.sh
  modules/ssh.sh
  package.json
Labels: ready to merge

#673 `treehouses tor ports` (fixes #655)
  modules/tor.sh
  package.json
Labels: please test & review

#1275 `treehouses services librespeed` (fixes #1217)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-librespeed.sh
  tests/services/librespeed.bats
  tests/test-helper.bash
Labels: PR, done, please test & review, ready to merge

#1092 `treehouses convert` audio and video files (fixes #1004)
  README.md
  _treehouses
  modules/convert.sh
  modules/help.sh
  package.json
Labels: high priority, please test & review

#1213 `treehouses services invoiceninja`
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-invoiceninja.sh
  tests/services/invoiceninja.bats
Labels: high priority, please test & review

#1283 `treehouses ssh fingerprint` (fixes #1280)
  README.md
  _treehouses
  modules/help.sh
  modules/ssh.sh
  package.json
Labels: high priority, please test & review

#1291 `treehouses` stop spinner with ctrl+z (fixes #1289)
  modules/globals.sh
  package.json
Labels: high priority, please test & review

#1287 `treehouses help` no whitespaces (fixes #1286)
  modules/help.sh
  package.json
Labels: high priority, please test & review

#1294 `treehouses couchdb` more EOF (fixes #1293)
  package.json
  services/install-couchdb.sh
Labels: high priority, please test & review

#1297 `treehouses kolibri` more EOF (fixes #1296)
  package.json
  services/install-kolibri.sh
Labels: high priority, please test & review

#1299 `treehouses librespeed` more EOF (fixes #1298)
  package.json
  services/install-librespeed.sh
Labels: high priority, please test & review

#1303 `treehouses led eid` (fixes #1282)
  README.md
  _treehouses
  modules/help.sh
  modules/led.sh
  package.json
  tests/led.bats
Labels: high priority, please test & review

#1302 `treehouses led lantern` (fixes #1175)
  _treehouses
  modules/help.sh
  modules/led.sh
  package.json
  tests/led.bats
Labels: high priority, please test & review

#1308 `treehouses changelog` new format (fixes #1304)
  modules/changelog.sh
  package.json
Labels: high priority, please test & review

#851 `treehouses wificountry` saved in `treehouse.conf` (fixes #689)
  cli.sh
  modules/bridge.sh
  modules/default.sh
  modules/staticwifi.sh
  modules/wifi.sh
  modules/wificountry.sh
  package.json
Labels: high priority, please test & review, ready to merge

#1318 update `services/README.md` (fixes #1306)
  package.json
  services/README.md
Labels: please test & review

#1307 `treehouses magazine` (fixes #1274)
  README.md
  _treehouses
  modules/help.sh
  modules/magazine.sh
  package.json
  tests/magazine.bats
Labels: enhancement, please test & review

#1331 `treehouses default network` wificountry (fixes #1325)
  modules/default.sh
  package.json
Labels: high priority, please test & review

#1352 `treehouses magazine hackspace` (fixes #1348)
  README.md
  _treehouses
  modules/help.sh
  modules/magazine.sh
  package.json
  tests/magazine.bats
Labels: enhancement, high priority, please test & review

#1349 `treehouses magazine magpi` output (fixes #1347)
  modules/magazine.sh
  package.json
Labels: done, high priority, please test & review

#1359 `treehouses services invoiceninja port` 8090 (fixes #1339)
  package.json
  services/install-invoiceninja.sh
Labels: high priority, please test & review

#1337 `treehouses services grocy` (fixes #1221)
  README.md
  modules/help.sh
  modules/services.sh
  package.json
  services/install-grocy.sh
  tests/services/grocy.bats
Labels: high priority, please test & review

#1353 `treehouses camera detect` (fixes #1315)
  README.md
  _treehouses
  modules/camera.sh
  modules/help.sh
  package.json
Labels: high priority, please test & review

#1371 `treehouses magazine magpi` tests (fixes #1328)
  package.json
  tests/magazine.bats
Labels: high priority, please test & review

#1372 `treehouses magazine magpi` & `hackspace` latest (fixes #1317)
  modules/magazine.sh
  package.json
Labels: high priority, please test & review

#1375 `treehouses magazine wireframe` (fixes #1373)
  README.md
  _treehouses
  modules/help.sh
  modules/magazine.sh
  package.json
  tests/magazine.bats
Labels: high priority, please test & review
