Repository treehouses/cli, pull requests merged in 2020-04, with the labels that each got.

#953 `treehouses detectbluetooth` refactor (fixes #952)(fixes #882)
  modules/detectbluetooth.sh
  package.json
Labels: bug, high priority, please test & review

#948 tests refactor (fixes #873) (fixes #857)
  package.json
  tests/README.md
  tests/apchannel.bats
  tests/blocker.bats
  tests/bluetooth.bats
  tests/cron.bats
  tests/detectbluetooth.bats
  tests/detectrpi.bats
  tests/ntp.bats
  tests/reboots.bats
  tests/remote.bats
  tests/services.bats
  tests/services/couchdb.bats
  tests/services/kolibri.bats
  tests/services/mariadb.bats
  tests/services/mastodon.bats
  tests/services/moodle.bats
  tests/services/netdata.bats
  tests/services/nextcloud.bats
  tests/services/ntopng.bats
  tests/services/pihole.bats
  tests/services/portainer.bats
  tests/services/privatebin.bats
  tests/services/seafile.bats
  tests/sshkey.bats
  tests/test-cli.sh
  tests/test-helper.bash
  tests/test.sh
  tests/tor.bats
  tests/wifi.bats
  tests/wifihidden.bats
Labels: enhancement, major, please test & review

#867 update README.md and `treehouses help`
  README.md
  modules/help.sh
  package.json
Labels: done, please test & review

#970 import only shell files of modules folder (fixes #969)
  cli.sh
  package.json
Labels: please test & review

#961 update `README.md` (fixes #960)
  README.md
Labels: enhancement

#972 `treehouses services icon oneline` (fixes #971)
  _treehouses
  modules/services.sh
  package.json
  services/install-privatebin.sh
Labels: please test & review

#958 `treehouses networkmode info` aphidden (fixes #933)(fixes #967)
  modules/apchannel.sh
  modules/networkmode.sh
  package.json
Labels: high priority, major, please test & review

#1017 `treehouses remote version` modify output (fixes #1015)
  modules/remote.sh
  package.json
Labels: high priority, please test & review

#1026 `treehouses services seafile info` improvement (fixes #1022)
  package.json
  services/install-seafile.sh
Labels: please test & review

#1012 `treehouses services <service>` check arm (fixes #943)
  modules/services.sh
  package.json
  services/install-couchdb.sh
  services/install-kolibri.sh
  services/install-mariadb.sh
  services/install-mastodon.sh
  services/install-moodle.sh
  services/install-netdata.sh
  services/install-nextcloud.sh
  services/install-ntopng.sh
  services/install-pihole.sh
  services/install-planet.sh
  services/install-portainer.sh
  services/install-privatebin.sh
  services/install-seafile.sh
Labels: high priority, please test & review

#1021 `treehouses remote json` (fixes #1013)
  README.md
  _treehouses
  modules/help.sh
  modules/remote.sh
  package.json
Labels: high priority, please test & review

#1027 `treehouses config` (fixes #983)
  README.md
  _treehouses
  cli.sh
  modules/config.sh
  modules/help.sh
  package.json
Labels: high priority, please test & review

#1024 `treehouses anime` (fixes #1008)
  modules/anime.sh
  package.json
Labels: enhancement, low priority, please test & review, ready to merge, vulnerability

#1036 `treehouses services available` based on arm type (fixes #1028)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#1038 `treehouses inspire` (fixes #1009)
  README.md
  _treehouses
  modules/help.sh
  modules/inspire.sh
  package.json
Labels: high priority, please test & review

#1030 `treehouses led heavymetal` (fixes #964)
  _treehouses
  modules/led.sh
  package.json
  tests/led.bats
Labels: high priority, please test & review

#1039 `treehouses networkmode` non-`info` message (fixes #931)
  modules/networkmode.sh
  package.json
Labels: high priority, please test & review

#977 `treehouses tor notice now` in report
  package.json
  templates/network/tor_report.sh
Labels: bug, high priority

#979 `treehouses sshtunnel notice now` in report
  package.json
  templates/network/tunnel_report.sh
Labels: bug, high priority

#1042 `treehouses version contributors` (fixes #1005)
  README.md
  _treehouses
  modules/help.sh
  modules/version.sh
  package.json
Labels: enhancement, high priority, please test & review

#1029 `treehouses services turtleblocksjs`
  README.md
  _treehouses
  modules/help.sh
  modules/services.sh
  package.json
  services/install-turtleblocksjs.sh
Labels: high priority, please test & review

#1031 `treehouses` subcommands without `eval` (fixes #1032)
  cli.sh
  package.json
Labels: high priority, please test & review

#1061 `treehouses remote allservices` (fixes #1044)
  README.md
  _treehouses
  modules/help.sh
  modules/remote.sh
  package.json
Labels: please test & review

#1057 `treehouses remote commands json` (fixes #1043)
  _treehouses
  modules/remote.sh
  package.json
Labels: high priority, please test & review

#1055 globals: `checkinternet` function (fixes #1054)
  modules/globals.sh
  package.json
Labels: high priority

#1056 `treehouses services <service> down` also rm tor (fixes #1051)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#1081 `treehouses remote` checkargn (fixes #1058)
  modules/remote.sh
  package.json
Labels: please test & review

#1077 `treehouses bluetooth status` (fixes #1048)
  README.md
  _treehouses
  modules/bluetooth.sh
  modules/help.sh
  package.json
Labels: please test & review

#1084 `treehouses remote check` (fixes #1083)
  README.md
  _treehouses
  modules/help.sh
  modules/remote.sh
  package.json
Labels: please test & review

#1076 `treehouses version contributors` alphabetical (fixes #1067)
  modules/version.sh
  package.json
Labels: please test & review

#1047 `treehouses shutdown` (fixes #992)
  README.md
  _treehouses
  modules/help.sh
  modules/shutdown.sh
  package.json
Labels: high priority, please test & review

#1085 `treehouses bluetooth` checkargn (fixes #1080)
  modules/bluetooth.sh
  package.json
Labels: please test & review

#1078 `treehouses bluetooth log` (fixes #1060)
  README.md
  _treehouses
  modules/bluetooth.sh
  modules/help.sh
  package.json
Labels: please test & review

#1089 `treehouses remote allservices` speedup (fixes #1082)
  modules/remote.sh
  package.json
Labels: please test & review

#1023 `treehouses wifi` & `wifihidden` combined (fixes #574)
  modules/wifi.sh
  modules/wifihidden.sh
  package.json
Labels: high priority, please test & review

#1096 `treehouses detectrpi` vagrant (fixes #1095)
  modules/detectrpi.sh
  package.json
Labels: high priority, please test & review

#560 `treehouses sshkey` remove deprecated (fixes #558)
  modules/sshkey.sh
  package.json
Labels: high priority, please test & review

#1094 `treehouses bluetooth restart` (fixes #1093)
  README.md
  _treehouses
  modules/bluetooth.sh
  modules/help.sh
  package.json
Labels: enhancement, high priority, please test & review

#1050 `treehouses services mongodb`
  README.md
  _treehouses
  modules/help.sh
  modules/services.sh
  package.json
  services/install-mongodb.sh
  tests/services/mongodb.bats
Labels: high priority, please test & review

#1100 `treehouses services ports` & `<service> url` fast (fixes #1099)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#1101 spinner when cli takes time
  cli.sh
  modules/globals.sh
  package.json
Labels: high priority, please test & review

#1037 treehouses services <service> environment (fixes #942)
  README.md
  _treehouses
  modules/help.sh
  modules/services.sh
  package.json
  services/README.md
  services/install-couchdb.sh
  services/install-kolibri.sh
  services/install-mariadb.sh
  services/install-mastodon.sh
  services/install-mongodb.sh
  services/install-moodle.sh
  services/install-netdata.sh
  services/install-nextcloud.sh
  services/install-ntopng.sh
  services/install-pihole.sh
  services/install-planet.sh
  services/install-portainer.sh
  services/install-privatebin.sh
  services/install-seafile.sh
  services/install-turtleblocksjs.sh
Labels: high priority, please test & review

#1107 `treehouses services seafile` local/tor (fixes #949)
  package.json
  services/install-seafile.sh
Labels: high priority, please test & review

#1110 `treehouses services ntopng autorun` compose (fixes #1103)
  services/install-ntopng.sh
Labels: high priority, please test & review

#1106 `treehouses detectwifi` (fixes #1104)
  README.md
  _treehouses
  modules/detectwifi.sh
  modules/help.sh
  package.json
  tests/detectwifi.bats
Labels: high priority, please test & review

#1059 update _treehouses to auto detect services (fixes # 1041)
  _treehouses
  package.json
Labels: high priority, please test & review

#1121 `treehouses bluetooth log follow` (fixes #1120)
  _treehouses
  modules/bluetooth.sh
  package.json
Labels: high priority, please test & review

#1111 `treehouses upgrade bluetooth`
  README.md
  _treehouses
  modules/help.sh
  modules/upgrade.sh
  package.json
  tests/upgrade.bats
Labels: high priority, please test & review

#1119 `treehouses upgrade check` (fixes #1116)
  README.md
  _treehouses
  modules/help.sh
  modules/upgrade.sh
  package.json
  tests/upgrade.bats
Labels: high priority, please test & review

#1141 `treehouses upgrade bluetooth <branch>` (fixes #1127)
  modules/upgrade.sh
  package.json
Labels: please test & review

#1122 `treehouses upgrade force` (fixes #1115)
  README.md
  _treehouses
  modules/help.sh
  modules/upgrade.sh
  package.json
  tests/upgrade.bats
Labels: please test & review

#1143 `treehouses services environment` without check (fixes #1113)
  README.md
  _treehouses
  modules/help.sh
  modules/services.sh
  package.json
Labels: high priority, please test & review

#1136 `treehouses led random` (fixes #989)
  _treehouses
  modules/led.sh
  package.json
  tests/led.bats
Labels: please test & review

#1131 add `.gitattributes` to force unix line endings (fixes #1126)
  .gitattributes
  package.json
Labels: please test & review

#1134 `treehouses tor notice` error message (fixes #936)
  modules/tor.sh
  package.json
Labels: please test & review

#1133 update `Vagrantfile` (fixes #1132)
  Vagrantfile
  package.json
Labels: high priority, please test & review

#1135 `treehouses detectrpi full` error message (fixes #951)
  modules/detectrpi.sh
  package.json
Labels: please test & review
