Repository treehouses/cli, pull requests merged in 2020-03, with the labels that each got.

#749 treehouses networkmode remove cat
  modules/networkmode.sh
Labels: please review

#751 treehouses password remove echo
  modules/password.sh
  package.json
Labels: please review

#739 treehouses led refactor (fixes #721)
  modules/led.sh
  package.json
Labels: enhancement, high priority, please review

#738 treehouses detectrpi for rogue RPI (fixes #733)
  modules/detectrpi.sh
  package.json
Labels: enhancement, high priority, please review

#755 treehouses carnival tab completion
  _treehouses
  package.json
Labels: bug

#750 treehouses usb remove cat
  modules/usb.sh
  package.json
Labels: please review

#737 treehouses container refactor (fixes #725)
  modules/container.sh
  package.json
Labels: enhancement, high priority, please review

#764 treehouses sdbench (fixes #730)
  README.md
  _treehouses
  cli.sh
  modules/help.sh
  modules/sdbench.sh
  package.json
Labels: please review

#744 treehouses services couchdb (fixes #742)
  modules/services.sh
  package.json
  templates/services/couchdb/couchdb_autorun
  templates/services/couchdb/couchdb_yml.sh
Labels: please review

#705 help function checkargn (fixes #697)
  cli.sh
  modules/detectrpi.sh
  modules/globals.sh
  package.json
Labels: enhancement, high priority, please review

#693 treehouses services <service> install (fixes #692)
  modules/services.sh
  package.json
  templates/services/install-scripts/install-kolibri.sh
  templates/services/install-scripts/install-mastodon.sh
  templates/services/install-scripts/install-moodle.sh
  templates/services/install-scripts/install-netdata.sh
  templates/services/install-scripts/install-nextcloud.sh
  templates/services/install-scripts/install-ntopng.sh
  templates/services/install-scripts/install-pihole.sh
  templates/services/install-scripts/install-planet.sh
  templates/services/install-scripts/install-portainer.sh
  templates/services/install-scripts/install-privatebin.sh
  templates/services/kolibri/kolibri_autorun
  templates/services/kolibri/kolibri_yml.sh
  templates/services/mastodon/mastodon_autorun
  templates/services/mastodon/mastodon_yml.sh
  templates/services/moodle/moodle_autorun
  templates/services/netdata/netdata_autorun
  templates/services/netdata/netdata_yml.sh
  templates/services/nextcloud/nextcloud_autorun
  templates/services/nextcloud/nextcloud_yml.sh
  templates/services/ntopng/ntopng_autorun
  templates/services/ntopng/ntopng_yml.sh
  templates/services/pihole/pihole_autorun
  templates/services/planet/planet_autorun
  templates/services/portainer/portainer_autorun
  templates/services/portainer/portainer_yml.sh
  templates/services/privatebin/privatebin_autorun
  templates/services/privatebin/privatebin_yml.sh
Labels: high priority, please review

#774 treehouses help aphidden (fixes #768)
  modules/aphidden.sh
  package.json
Labels: please review

#775 treehouses help ap (fixes #770)
  modules/ap.sh
  package.json
Labels: please review

#777 treehouses help button (fixes #771)
  modules/button.sh
  package.json
Labels: please review

#778 treehouses services tor check (fixes #773)
  modules/services.sh
  package.json
Labels: please review

#786 treehouses password not empty (fixes #754)
  modules/password.sh
  package.json
Labels: bug, high priority

#793 treehouses detectrpi add models (fixes #792)
  modules/detectrpi.sh
  package.json
Labels: bug, high priority, please review

#806 treehouses bridge remove cat
  modules/bridge.sh
  package.json
Labels: low priority, please review

#825 treehouses services installed check srv directory (fixes #824)
  modules/services.sh
  package.json
Labels: high priority

#779 treehouses wificountry country code check (fixes #756)
  modules/wificountry.sh
  package.json
Labels: please review

#823 treehouses services running parsing (fixes #820)
  modules/services.sh
  package.json
Labels: high priority

#794 treehouses detectbluetooth & checkwrpi (fixes #789)(fixes #790)
  README.md
  _treehouses
  cli.sh
  modules/detectbluetooth.sh
  modules/globals.sh
  modules/help.sh
  package.json
Labels: bug, enhancement, high priority, please review

#850 missing commands in _treehouses
  _treehouses
  package.json
Labels: done, high priority, please test & review

#839 treehouses services mariadb
  README.md
  _treehouses
  modules/help.sh
  modules/services.sh
  package.json
  services/install-mariadb.sh
Labels: high priority, please test & review

#860 treehouses services couchdb url (fixes #834)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#861 treehouses services check_space on install (fixes #859)
  modules/services.sh
  package.json
Labels: high priority

#854 treehouses services url (fixes #833)
  modules/services.sh
  package.json
Labels: please test & review

#853 treehouses staticwifi min arguments check (fixes #710)
  modules/staticwifi.sh
  package.json
Labels: please test & review

#874 include all modules automatically (fixes #872)
  cli.sh
  package.json
Labels: high priority, please test & review

#868 treehouses bluetooth (fixes #865)
  modules/bluetooth.sh
  package.json
Labels: high priority, please test & review

#875 treehouses services up refactor (fixes #827)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#882 treehouses services <service> icon (fixes #846)
  modules/services.sh
  package.json
  services/install-couchdb.sh
  services/install-kolibri.sh
  services/install-mariadb.sh
  services/install-mastodon.sh
  services/install-moodle.sh
  services/install-netdata.sh
  services/install-nextcloud.sh
  services/install-ntopng.sh
  services/install-pihole.sh
  services/install-planet.sh
  services/install-portainer.sh
  services/install-privatebin.sh
Labels: high priority, please test & review

#890 treehouses remote 7 args check (fixes #891)
  modules/remote.sh
  package.json
Labels: please test & review

#898 treehouses checkargn overhaul
  modules/ap.sh
  modules/apchannel.sh
  modules/aphidden.sh
  modules/blocker.sh
  modules/bluetooth.sh
  modules/bluetoothid.sh
  modules/bootoption.sh
  modules/bridge.sh
  modules/burn.sh
  modules/button.sh
  modules/camera.sh
  modules/clone.sh
  modules/container.sh
  modules/coralenv.sh
  modules/cron.sh
  modules/default.sh
  modules/detect.sh
  modules/detectbluetooth.sh
  modules/detectrpi.sh
  modules/discover.sh
  modules/ethernet.sh
  modules/expandfs.sh
  modules/feedback.sh
  modules/globals.sh
  modules/help.sh
  modules/image.sh
  modules/internet.sh
  modules/led.sh
  modules/locale.sh
  modules/log.sh
  modules/memory.sh
  modules/networkmode.sh
  modules/ntp.sh
  modules/openvpn.sh
  modules/password.sh
  modules/rebootneeded.sh
  modules/reboots.sh
  modules/remote.sh
  modules/rename.sh
  modules/restore.sh
  modules/rtc.sh
  modules/sdbench.sh
  modules/services.sh
  modules/ssh.sh
  modules/sshkey.sh
  modules/sshtunnel.sh
  modules/staticwifi.sh
  modules/temperature.sh
  modules/timezone.sh
  modules/tor.sh
  modules/upgrade.sh
  modules/usb.sh
  modules/verbose.sh
  modules/version.sh
  modules/vnc.sh
  modules/wifi.sh
  modules/wificountry.sh
  modules/wifihidden.sh
  modules/wifistatus.sh
  package.json
Labels: please test & review

#883 services README.md (fixes #878)
  package.json
  services/README.md
Labels: high priority, please test & review

#856 treehouses services seafile
  README.md
  _treehouses
  modules/help.sh
  modules/services.sh
  package.json
  services/install-seafile.sh
  tests/seafile.bats
Labels: high priority, please test & review

#905 treehouses help services & remove deprecated (fixes #904)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#893 treehouses services check on file (fixes #881)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#877 treehouses services docker dns retry (fixes #832)
  modules/services.sh
Labels: high priority, please test & review

#895 treehouses services remove get_port (fixes #880)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#902 treehouses services <service> cleanup autorun (fixes #901)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#913 treehouses tests no sshkey deleteall (fixes #912)
  package.json
  tests/sshkey.bats
Labels: done, please test & review, ready to merge

#916 treehouses tests services url only (fixes #915)
  package.json
  tests/couchdb.bats
  tests/kolibri.bats
  tests/mariadb.bats
  tests/mastodon.bats
  tests/moodle.bats
  tests/netdata.bats
  tests/nextcloud.bats
  tests/ntopng.bats
  tests/pihole.bats
  tests/portainer.bats
  tests/privatebin.bats
  tests/seafile.bats
  tests/services.bats
Labels: done, enhancement, major, please test & review

#914 treehouses tests services <service> icon (fixes #900)
  package.json
  tests/couchdb.bats
  tests/kolibri.bats
  tests/mariadb.bats
  tests/mastodon.bats
  tests/moodle.bats
  tests/netdata.bats
  tests/nextcloud.bats
  tests/ntopng.bats
  tests/pihole.bats
  tests/portainer.bats
  tests/privatebin.bats
  tests/seafile.bats
  tests/services.bats
Labels: enhancement, major, please test & review, ready to merge

#903 treehouses sshkey github <command> check (fixes #889)
  modules/sshkey.sh
  package.json
Labels: please test & review

#919 treehouses services available exclude README.md (fixes #917)
  _treehouses
  modules/services.sh
  package.json
Labels: high priority, please test & review

#921 treehouses services <service> port refactor (fixes #920)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#922 treehouses services moodle refactor (fixes #918)
  package.json
  services/install-moodle.sh
Labels: high priority, please test & review

#925 treehouses services checkargn (fixes #923)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#930 treehouses services installed full check (fixes #928)
  modules/services.sh
  package.json
Labels: please test & review

#805 treehouses ap & aphidden merger (fixes #804)
  modules/ap.sh
  modules/aphidden.sh
  package.json
Labels: high priority, low priority, please test & review

#938 `treehouses tor notice now` internal feedback (fixes #934)
  modules/tor.sh
  package.json
Labels: bug, high priority, please test & review

#939 treehouses feedback remove checkargn (fixes #934)
  modules/feedback.sh
  package.json
Labels: bug, high priority, please test & review

#940 treehouses services improve outputs (fixes #932)
  modules/services.sh
  package.json
Labels: please test & review

#927 `treehouses services <service>` file check (fixes #879)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#941 treehouses no globals & no config (fixes #926)
  cli.sh
  package.json
Labels: please test & review

#957 automate _treehouses (fixes #956)
  _treehouses
  package.json
Labels: enhancement, please test & review, ready to merge

#944 `treehouses detectarm`
  README.md
  _treehouses
  modules/detectarm.sh
  modules/help.sh
  package.json
  tests/detectarm.bats
Labels: please test & review
