Repository treehouses/cli, pull requests merged in 2020-08, with the labels that each got.

#1740 `treehouses magazines` README.md (fixes #1692)
  magazines/README.md
  package.json
Labels: done

#1725 `treehouses shadowsocks` refactor
  modules/shadowsocks.sh
  package.json
Labels: please test & review

#1738 `treehouses remote statuspage` with storage (fixes #1723)
  README.md
  _treehouses
  modules/help.sh
  modules/remote.sh
  package.json
  tests/remote.bats
Labels: high priority, please test & review

#1747 `treehouses internet reverse` test (fixes #1749)
  package.json
  tests/internet.bats
Labels: please test & review

#1742 `treehouses memory` test (fixes #1741)
  package.json
  tests/memory.bats
Labels: please test & review

#1745 `treehouses` bash completion dynamic path (fixes #1739)
  _treehouses
  package.json
Labels: please test & review

#1751 `treehouses internet reverse` refactor (fixes #1737)
  modules/internet.sh
  package.json
Labels: please test & review

#1754 `treehouses internet reverse` check internet (fixes #1736)
  modules/internet.sh
  package.json
Labels: high priority, please test & review

#1758 `treehouses shadowsocks` interactive mode
  modules/shadowsocks.sh
  package.json
Labels: high priority, please test & review

#1704 `treehouses storage` (fixes #1672)
  README.md
  _treehouses
  modules/help.sh
  modules/storage.sh
  package.json
  tests/storage.bats
Labels: high priority, please test & review

#1693 `treehouses ssh 2fa` (fixes #1646)
  README.md
  _treehouses
  modules/help.sh
  modules/ssh.sh
  package.json
Labels: high priority, please test & review

#1768 `treehouses ssh 2fa` enhancements (fixes #1766)
  modules/ssh.sh
  package.json
Labels: please test & review

#1767 `treehouses version remote` (fixes #1764)
  README.md
  _treehouses
  modules/help.sh
  modules/version.sh
  package.json
  tests/version.bats
Labels: high priority, please test & review

#1769 `treehouses storage` output overview (fixes #1760)
  modules/storage.sh
  package.json
Labels: please test & review

#1775 `treehouses bluetooth pause` (fixes #1774)
  modules/bluetooth.sh
  package.json
Labels: please test & review

#1795 `treehouses internet` based on netcat (fixes #1791)
  modules/internet.sh
  package.json
Labels: help wanted, high priority, please test & review

#1826 `treehouses services <service> config edit` nospin (fixes #1816)
  modules/services.sh
  package.json
Labels: high priority, please test & review

#1809 new `check_missing_binary <binary> [instructions]` (fixes #1807)
  modules/globals.sh
  package.json
Labels: please test & review

#1823 `treehouses usb` install instructions (fixes #1820)
  modules/usb.sh
  package.json
Labels: blocked, enhancement

#1824 `treehouses picture` install instructions (fixes #1819)
  modules/picture.sh
  package.json
Labels: blocked, enhancement

#1822 `treehouses services` install instructions (fixes 1821)
  modules/services.sh
  package.json
Labels: blocked, enhancement

#1825 `treehouses remote statuspage` with wificountry (fixes #1815)
  modules/remote.sh
  package.json
Labels: please test & review
